name: pts2_fcc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.20.1
  get: ^4.6.6
  dio: ^5.1.2
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.2
  connectivity_plus: ^6.1.3
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  share_plus: ^10.1.3
  flutter_native_splash: ^2.2.19
  
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Garnett
      fonts:
        - asset: assets/fonts/Garnett-Bold.ttf
          weight: 700
        - asset: assets/fonts/Garnett-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Garnett-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#000000"
  image: assets/images/fulllogo.png